---
- name: Backup for R1
  hosts: R1
  gather_facts: false
  connection: local
 
  tasks:
   - name: Show the Startup Configuration
     ios_command:
       commands:
         - show startup-config
     register: startupconfig
 
   - name: SAVE OUTPUT TO ./backups/
     copy:
       content: "{{ startupconfig.stdout[0] }}"
       dest: "backups/R1_startup.txt"

   - name: Show the Running Configuration
     ios_command:
       commands:
         - show running-config
     register: config
 
   - name: SAVE OUTPUT TO ./backups/
     copy:
       content: "{{ config.stdout[0] }}"
       dest: "backups/R1_run.txt"